### ISSUE TITLE
hs_auth API v2 support

### ISSUE THREAD

**Issue by seanjparker** [unicsmcr/hs_apply#71]
Tracking issue for converting `hs_apply` to use `hs_auth` API v2.

- [x] Auth API v2: Integrate new auth system with RequestAuthentication (#72)
- [x] Auth API v2: Refactor frontend to use resources rather than AuthLevels (#74)
- [ ] Auth API v2: Use Request object to add arguments to the URI in RequestAuthentication (#75)
